### ISSUE TITLE
MongoDB error with logview.jsp

### ISSUE THREAD

**Issue by dsato80** [hulop/MapService#6]
MongoDB version: 3.6.2

```
[ERROR   ] SRVE0777E: Exception thrown by application class 'com.mongodb.connection.ProtocolHelper.getCommandFailureException:115'
com.mongodb.MongoCommandException: Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "The 'cursor' option is required, except for aggregate with the explain argument", "code" : 9, "codeName" : "FailedToParse" }
	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:176)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:207)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:113)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:257)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:253)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:435)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:408)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:253)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:67)
	at com.mongodb.Mongo.execute(Mongo.java:836)
	at com.mongodb.Mongo$2.execute(Mongo.java:823)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1455)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1380)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1366)
	at hulop.hokoukukan.utils.MongoAdapter.getLogStats(MongoAdapter.java:298)
	at hulop.hokoukukan.utils.COSAdapter.getLogStats(COSAdapter.java:278)
	at hulop.hokoukukan.bean.DatabaseBean.getLogStats(DatabaseBean.java:374)
	at hulop.hokoukukan.servlet.LoggingServlet.doGet(LoggingServlet.java:92)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at [internal classes]
	at hulop.hokoukukan.servlet.GZIPFilter.doFilter(GZIPFilter.java:99)
	at hulop.hokoukukan.servlet.GZIPFilter.doFilter(GZIPFilter.java:59)
	at hulop.hokoukukan.servlet.FileFilter.doFilter(FileFilter.java:77)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at [internal classes]
```

**Comment by itohtaka** [comment]
https://docs.mongodb.com/manual/release-notes/3.6-compatibility/#aggregate-compatibility

>MongoDB 3.6 removes the option for the aggregate command to return its results as a single document.
If you run the aggregate command, you must include either the cursor option or the explain option.
Rather than run the aggregate command directly, most users should use the db.collection.aggregate() helper provided in the mongo shell or the equivalent helper in their driver. These helpers return a cursor unless using the explain option.
